# This theme is based on https://github.com/jekyll/minima
# Please refer above link to know the available configurations

title: "RFID Tapping System"
email: e21148@eng.pdn.ac.lk
description: >- # this means to ignore newlines until "baseurl:"
  Production-ready RFID tracking system with real-time analytics, game mechanics, and IoT integration.
  Built for EngEx 2025.

# Build settings
remote_theme: cepdnaclk/eYY-project-theme
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom Settings
show_downloads: true
google_analytics:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be defined by specifically listing the full path to the
# item or by listing all the files that match a pattern, such as `*.gem`.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false

mermaid:
  enabled: true
